--------------------------------------------------------
--  File created - Thứ Năm-tháng 10-23-2025   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence CASE_DOCUMENT_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "HIEUDNT"."CASE_DOCUMENT_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 50 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence DOCUMENT_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "HIEUDNT"."DOCUMENT_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 50 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence PERSON_DOCUMENT_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "HIEUDNT"."PERSON_DOCUMENT_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 50 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence iseq$$_75924
--------------------------------------------------------

   CREATE SEQUENCE  "HIEUDNT"."iseq$$_75924"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Table BORROWER
--------------------------------------------------------

  CREATE TABLE "HIEUDNT"."BORROWER" 
   (	"ID_BORROWER" NUMBER(19,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"DEPARTMENT" VARCHAR2(255 CHAR), 
	"FULL_NAME" VARCHAR2(255 CHAR), 
	"ID_CARD_NUMBER" VARCHAR2(255 CHAR), 
	"PHONE_NUMBER" VARCHAR2(255 CHAR), 
	"POSITION" VARCHAR2(255 CHAR)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table DOCUMENT
--------------------------------------------------------

  CREATE TABLE "HIEUDNT"."DOCUMENT" 
   (	"ID_DOCUMENT" NUMBER(19,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"CREATED_DATE" DATE, 
	"DESCRIPTION" VARCHAR2(500 CHAR), 
	"DOCUMENT_CODE" VARCHAR2(50 CHAR), 
	"EVENT_DATE" DATE, 
	"NOTE" CLOB, 
	"STATUS" VARCHAR2(50 CHAR), 
	"TITLE" VARCHAR2(255 CHAR), 
	"TYPE" VARCHAR2(100 CHAR)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" 
 LOB ("NOTE") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW 4000 CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) ;
--------------------------------------------------------
--  DDL for Table DOCUMENT_CATEGORY
--------------------------------------------------------

  CREATE TABLE "HIEUDNT"."DOCUMENT_CATEGORY" 
   (	"ID_DOCUMENT_CATEGORY" NUMBER(19,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"CONTENT" VARCHAR2(255 CHAR), 
	"NOTE" VARCHAR2(255 CHAR), 
	"RETENTION_PERIOD" VARCHAR2(100 CHAR), 
	"SYMBOL" VARCHAR2(50 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table DOCUMENT_SET
--------------------------------------------------------

  CREATE TABLE "HIEUDNT"."DOCUMENT_SET" 
   (	"ID_DOCUMENT_SET" NUMBER(19,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"AREA" VARCHAR2(100 CHAR), 
	"DEPARTMENT" VARCHAR2(100 CHAR), 
	"DOCUMENT_CODE" VARCHAR2(50 CHAR), 
	"NOTE" CLOB, 
	"OPENED_DATE" DATE, 
	"STATUS" VARCHAR2(50 CHAR), 
	"CATEGORY_ID" NUMBER(19,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" 
 LOB ("NOTE") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW 4000 CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) ;
--------------------------------------------------------
--  DDL for Table LIBRARIAN
--------------------------------------------------------

  CREATE TABLE "HIEUDNT"."LIBRARIAN" 
   (	"IDLIBRARIAN" NUMBER(19,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"EMAIL" VARCHAR2(255 CHAR), 
	"FULL_NAME" VARCHAR2(255 CHAR), 
	"PASSWORD" VARCHAR2(255 CHAR), 
	"PHONE_NUMBER" VARCHAR2(255 CHAR), 
	"POSITION" VARCHAR2(255 CHAR), 
	"RANK" VARCHAR2(255 CHAR), 
	"STAFF_CODE" VARCHAR2(255 CHAR), 
	"USERNAME" VARCHAR2(255 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table REQUEST_DOCUMENT
--------------------------------------------------------

  CREATE TABLE "HIEUDNT"."REQUEST_DOCUMENT" 
   (	"ID_REQUEST_DOCUMENT" NUMBER(19,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"ATTACHMENT_PATH" VARCHAR2(255 CHAR), 
	"BORROW_DATE" DATE, 
	"COPY_TYPE" VARCHAR2(255 CHAR), 
	"DOCUMENT_NUMBER" VARCHAR2(255 CHAR), 
	"EXTENSION_COUNT" NUMBER(10,0), 
	"RETURN_DEADLINE" DATE, 
	"SIGNER" VARCHAR2(255 CHAR), 
	"BORROWER_ID" NUMBER(19,0), 
	"DOCUMENT_SET_ID" NUMBER(19,0), 
	"LIBRARIAN_ID" NUMBER(19,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
REM INSERTING into HIEUDNT.BORROWER
SET DEFINE OFF;
REM INSERTING into HIEUDNT.DOCUMENT
SET DEFINE OFF;
REM INSERTING into HIEUDNT.DOCUMENT_CATEGORY
SET DEFINE OFF;
Insert into HIEUDNT.DOCUMENT_CATEGORY (ID_DOCUMENT_CATEGORY,CONTENT,NOTE,RETENTION_PERIOD,SYMBOL) values (1,'Hồ sơ pháp nhân: Cơ quan, tổ chức mời, bảo lãnh người nước ngoài nhập cảnh, cấp thị thực, gia hạn tạm trú, cấp thẻ tạm trú; Cơ quan, tổ chức, doanh nghiệp đăng ký làm thẻ thủ tục đề nghị cấp giấy thông hành cho công dân Việt Nam',null,'15','PN');
Insert into HIEUDNT.DOCUMENT_CATEGORY (ID_DOCUMENT_CATEGORY,CONTENT,NOTE,RETENTION_PERIOD,SYMBOL) values (2,'Hồ sơ kiểm tra, xét duyệt nhân sự cấp phép nhập cảnh cho người nước ngoài ở Việt Nam',null,'5','NK');
Insert into HIEUDNT.DOCUMENT_CATEGORY (ID_DOCUMENT_CATEGORY,CONTENT,NOTE,RETENTION_PERIOD,SYMBOL) values (3,'Hồ sơ kiểm tra nhân sự doanh nhân nước ngoài cấp thẻ ABTC',null,'5','AC');
Insert into HIEUDNT.DOCUMENT_CATEGORY (ID_DOCUMENT_CATEGORY,CONTENT,NOTE,RETENTION_PERIOD,SYMBOL) values (4,'Hồ sơ cấp thẻ tạm trú cho người nước ngoài; cấp giấy phép cho người nước ngoài vào khu vực cấm, khu vực biên giới',null,'5','NT');
Insert into HIEUDNT.DOCUMENT_CATEGORY (ID_DOCUMENT_CATEGORY,CONTENT,NOTE,RETENTION_PERIOD,SYMBOL) values (5,'Hồ sơ xét, cấp miễn thị thực cho người Việt Nam định cư ở nước ngoài và người nước ngoài là vợ, chồng, con của người nước ngoài hoặc của công dân Việt Nam',null,'10','MT');
Insert into HIEUDNT.DOCUMENT_CATEGORY (ID_DOCUMENT_CATEGORY,CONTENT,NOTE,RETENTION_PERIOD,SYMBOL) values (6,'Hồ sơ người nước ngoài xin thường trú',null,null,'TH');
Insert into HIEUDNT.DOCUMENT_CATEGORY (ID_DOCUMENT_CATEGORY,CONTENT,NOTE,RETENTION_PERIOD,SYMBOL) values (7,'Hồ sơ cấp giấy phép xuất nhập cảnh cho người nước ngoài không có hộ chiếu thường trú tại Việt Nam',null,'5','GP');
Insert into HIEUDNT.DOCUMENT_CATEGORY (ID_DOCUMENT_CATEGORY,CONTENT,NOTE,RETENTION_PERIOD,SYMBOL) values (8,'Hồ sơ kiểm tra nhân sự người nước ngoài xin con nuôi, xin kết hôn với người Việt Nam',null,null,'NH');
Insert into HIEUDNT.DOCUMENT_CATEGORY (ID_DOCUMENT_CATEGORY,CONTENT,NOTE,RETENTION_PERIOD,SYMBOL) values (9,'Hồ sơ người nước ngoài xin nhập quốc tịch Việt Nam',null,'40','VN');
Insert into HIEUDNT.DOCUMENT_CATEGORY (ID_DOCUMENT_CATEGORY,CONTENT,NOTE,RETENTION_PERIOD,SYMBOL) values (10,'Hồ sơ xin thôi quốc tịch Việt Nam',null,null,'VQ');
Insert into HIEUDNT.DOCUMENT_CATEGORY (ID_DOCUMENT_CATEGORY,CONTENT,NOTE,RETENTION_PERIOD,SYMBOL) values (11,'Hồ sơ người nước ngoài (gốc Việt Nam) xin trở lại quốc tịch Việt Nam',null,null,'VK');
Insert into HIEUDNT.DOCUMENT_CATEGORY (ID_DOCUMENT_CATEGORY,CONTENT,NOTE,RETENTION_PERIOD,SYMBOL) values (12,'Hồ sơ người Việt Nam định cư ở nước ngoài đăng ký giữ quốc tịch Việt Nam',null,null,'VG');
Insert into HIEUDNT.DOCUMENT_CATEGORY (ID_DOCUMENT_CATEGORY,CONTENT,NOTE,RETENTION_PERIOD,SYMBOL) values (13,'Hồ sơ người nước ngoài bị trục xuất',null,null,'TR');
Insert into HIEUDNT.DOCUMENT_CATEGORY (ID_DOCUMENT_CATEGORY,CONTENT,NOTE,RETENTION_PERIOD,SYMBOL) values (14,'Hồ sơ cấp hộ chiếu, tem AB cho công dân Việt Nam',null,null,'HC');
Insert into HIEUDNT.DOCUMENT_CATEGORY (ID_DOCUMENT_CATEGORY,CONTENT,NOTE,RETENTION_PERIOD,SYMBOL) values (15,'Hồ sơ cấp hộ chiếu có yếu tố can thiệp của nước ngoài',null,null,'HN');
Insert into HIEUDNT.DOCUMENT_CATEGORY (ID_DOCUMENT_CATEGORY,CONTENT,NOTE,RETENTION_PERIOD,SYMBOL) values (16,'Hồ sơ cấp giấy thông hành biên giới',null,null,'TB');
Insert into HIEUDNT.DOCUMENT_CATEGORY (ID_DOCUMENT_CATEGORY,CONTENT,NOTE,RETENTION_PERIOD,SYMBOL) values (17,'Hồ sơ kiểm tra nhân sự cấp hộ chiếu của công dân Việt Nam ở nước ngoài',null,null,'HD');
Insert into HIEUDNT.DOCUMENT_CATEGORY (ID_DOCUMENT_CATEGORY,CONTENT,NOTE,RETENTION_PERIOD,SYMBOL) values (18,'Hồ sơ cấp thẻ ABTC cho doanh nhân Việt Nam',null,null,'AP');
Insert into HIEUDNT.DOCUMENT_CATEGORY (ID_DOCUMENT_CATEGORY,CONTENT,NOTE,RETENTION_PERIOD,SYMBOL) values (19,'Hồ sơ công dân Việt Nam định cư ở nước ngoài đăng ký thường trú tại Việt Nam',null,null,'VH');
Insert into HIEUDNT.DOCUMENT_CATEGORY (ID_DOCUMENT_CATEGORY,CONTENT,NOTE,RETENTION_PERIOD,SYMBOL) values (20,'Hồ sơ nhận trở lại công dân Việt Nam không được phía nước ngoài cho cư trú',null,null,'HH');
Insert into HIEUDNT.DOCUMENT_CATEGORY (ID_DOCUMENT_CATEGORY,CONTENT,NOTE,RETENTION_PERIOD,SYMBOL) values (21,'Hồ sơ công dân Việt Nam sử dụng hộ chiếu có chi tiết nhân thân không đúng, gọi tắt là "Hồ sơ CT28"',null,null,'CT');
Insert into HIEUDNT.DOCUMENT_CATEGORY (ID_DOCUMENT_CATEGORY,CONTENT,NOTE,RETENTION_PERIOD,SYMBOL) values (22,'Hồ sơ đối tượng chưa cho nhập cảnh, tạm hoãn xuất cảnh',null,null,'ĐT');
Insert into HIEUDNT.DOCUMENT_CATEGORY (ID_DOCUMENT_CATEGORY,CONTENT,NOTE,RETENTION_PERIOD,SYMBOL) values (23,'Hồ sơ hủy, phục hồi giá trị hộ chiếu, thị thực, giấy tờ xuất nhập cảnh',null,null,'HG');
Insert into HIEUDNT.DOCUMENT_CATEGORY (ID_DOCUMENT_CATEGORY,CONTENT,NOTE,RETENTION_PERIOD,SYMBOL) values (24,'Hồ sơ cung cấp thông tin xuất nhập cảnh',null,null,'CC');
Insert into HIEUDNT.DOCUMENT_CATEGORY (ID_DOCUMENT_CATEGORY,CONTENT,NOTE,RETENTION_PERIOD,SYMBOL) values (25,'Hồ sơ cấp thị thực điện tử',null,null,'TĐ');
Insert into HIEUDNT.DOCUMENT_CATEGORY (ID_DOCUMENT_CATEGORY,CONTENT,NOTE,RETENTION_PERIOD,SYMBOL) values (26,'Hồ sơ xử lý vi phạm xuất nhập cảnh',null,null,'VP');
REM INSERTING into HIEUDNT.DOCUMENT_SET
SET DEFINE OFF;
REM INSERTING into HIEUDNT.LIBRARIAN
SET DEFINE OFF;
Insert into HIEUDNT.LIBRARIAN (IDLIBRARIAN,EMAIL,FULL_NAME,PASSWORD,PHONE_NUMBER,POSITION,RANK,STAFF_CODE,USERNAME) values (3,'thaopm@gmail.com','Phạm Minh Thao','B6FC1B54FC09ECCF4303A805717C9F624DB19CBF5C267DC351EB625DDE1C2CD1','0905123456','Thủ thư chính','Thiếu tá','500-432','thaopm');
REM INSERTING into HIEUDNT.REQUEST_DOCUMENT
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index UK_285TCIUBTXSPYLV69BKEKQ2LM
--------------------------------------------------------

  CREATE UNIQUE INDEX "HIEUDNT"."UK_285TCIUBTXSPYLV69BKEKQ2LM" ON "HIEUDNT"."DOCUMENT_SET" ("DOCUMENT_CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index UK_OUWPWSSTWINXHT1FVTRQS3KD3
--------------------------------------------------------

  CREATE UNIQUE INDEX "HIEUDNT"."UK_OUWPWSSTWINXHT1FVTRQS3KD3" ON "HIEUDNT"."DOCUMENT" ("DOCUMENT_CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table REQUEST_DOCUMENT
--------------------------------------------------------

  ALTER TABLE "HIEUDNT"."REQUEST_DOCUMENT" MODIFY ("ID_REQUEST_DOCUMENT" NOT NULL ENABLE);
  ALTER TABLE "HIEUDNT"."REQUEST_DOCUMENT" MODIFY ("EXTENSION_COUNT" NOT NULL ENABLE);
  ALTER TABLE "HIEUDNT"."REQUEST_DOCUMENT" ADD PRIMARY KEY ("ID_REQUEST_DOCUMENT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table DOCUMENT
--------------------------------------------------------

  ALTER TABLE "HIEUDNT"."DOCUMENT" MODIFY ("ID_DOCUMENT" NOT NULL ENABLE);
  ALTER TABLE "HIEUDNT"."DOCUMENT" MODIFY ("DOCUMENT_CODE" NOT NULL ENABLE);
  ALTER TABLE "HIEUDNT"."DOCUMENT" MODIFY ("TITLE" NOT NULL ENABLE);
  ALTER TABLE "HIEUDNT"."DOCUMENT" ADD PRIMARY KEY ("ID_DOCUMENT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HIEUDNT"."DOCUMENT" ADD CONSTRAINT "UK_OUWPWSSTWINXHT1FVTRQS3KD3" UNIQUE ("DOCUMENT_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table DOCUMENT_SET
--------------------------------------------------------

  ALTER TABLE "HIEUDNT"."DOCUMENT_SET" MODIFY ("ID_DOCUMENT_SET" NOT NULL ENABLE);
  ALTER TABLE "HIEUDNT"."DOCUMENT_SET" MODIFY ("DOCUMENT_CODE" NOT NULL ENABLE);
  ALTER TABLE "HIEUDNT"."DOCUMENT_SET" ADD PRIMARY KEY ("ID_DOCUMENT_SET")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HIEUDNT"."DOCUMENT_SET" ADD CONSTRAINT "UK_285TCIUBTXSPYLV69BKEKQ2LM" UNIQUE ("DOCUMENT_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table BORROWER
--------------------------------------------------------

  ALTER TABLE "HIEUDNT"."BORROWER" MODIFY ("ID_BORROWER" NOT NULL ENABLE);
  ALTER TABLE "HIEUDNT"."BORROWER" ADD PRIMARY KEY ("ID_BORROWER")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table DOCUMENT_CATEGORY
--------------------------------------------------------

  ALTER TABLE "HIEUDNT"."DOCUMENT_CATEGORY" MODIFY ("ID_DOCUMENT_CATEGORY" NOT NULL ENABLE);
  ALTER TABLE "HIEUDNT"."DOCUMENT_CATEGORY" MODIFY ("CONTENT" NOT NULL ENABLE);
  ALTER TABLE "HIEUDNT"."DOCUMENT_CATEGORY" MODIFY ("SYMBOL" NOT NULL ENABLE);
  ALTER TABLE "HIEUDNT"."DOCUMENT_CATEGORY" ADD PRIMARY KEY ("ID_DOCUMENT_CATEGORY")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table LIBRARIAN
--------------------------------------------------------

  ALTER TABLE "HIEUDNT"."LIBRARIAN" MODIFY ("IDLIBRARIAN" NOT NULL ENABLE);
  ALTER TABLE "HIEUDNT"."LIBRARIAN" ADD PRIMARY KEY ("IDLIBRARIAN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table DOCUMENT_SET
--------------------------------------------------------

  ALTER TABLE "HIEUDNT"."DOCUMENT_SET" ADD CONSTRAINT "FKT2MTFDNE2Y9Y9BJWQFFKO68C3" FOREIGN KEY ("CATEGORY_ID")
	  REFERENCES "HIEUDNT"."DOCUMENT_CATEGORY" ("ID_DOCUMENT_CATEGORY") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table REQUEST_DOCUMENT
--------------------------------------------------------

  ALTER TABLE "HIEUDNT"."REQUEST_DOCUMENT" ADD CONSTRAINT "FKRYU7Q6G5H324763RDUDKHPYKU" FOREIGN KEY ("BORROWER_ID")
	  REFERENCES "HIEUDNT"."BORROWER" ("ID_BORROWER") ENABLE;
  ALTER TABLE "HIEUDNT"."REQUEST_DOCUMENT" ADD CONSTRAINT "FKPFVK9B2QNXXHDU4VE97ULLYJ7" FOREIGN KEY ("DOCUMENT_SET_ID")
	  REFERENCES "HIEUDNT"."DOCUMENT_SET" ("ID_DOCUMENT_SET") ENABLE;
  ALTER TABLE "HIEUDNT"."REQUEST_DOCUMENT" ADD CONSTRAINT "FKTP9SD0LGJKBOANDBAS2SNJRUM" FOREIGN KEY ("LIBRARIAN_ID")
	  REFERENCES "HIEUDNT"."LIBRARIAN" ("IDLIBRARIAN") ENABLE;
