# -------------------
# ? Server settings
# -------------------
server.port=8080
spring.thymeleaf.cache=false

# -------------------
# ? Oracle Database
# -------------------
spring.datasource.url=jdbc:oracle:thin:@localhost:1521/XEPDB1
<<<<<<< HEAD
spring.datasource.username=vth
spring.datasource.password=Abc@1234
=======
spring.datasource.username=hieudnt
spring.datasource.password=Donguyentrunghieu12@
>>>>>>> origin/main
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# -------------------
# ? JPA / Hibernate
# -------------------
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect
<<<<<<< HEAD
spring.jpa.properties.hibernate.default_schema=vth
=======
spring.jpa.properties.hibernate.default_schema=hieudnt
>>>>>>> origin/main
